version: '3'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
    ports:
      - "8000:3000"
    command: npm start